いっぱいみてね
ououno/ichiyasaGitSample pull request #2
Opened 2024-01-16 04:18 UTC by ououno

2024-01-16 04:22 UTC, sota777 commented
いろんなトコロ見せてくれるのカナ？？
楽しみだなぁ～♥

2024-01-16 04:33 UTC, YamamotoHazuki commented
いろんな😍💕トコロを見せてくれるのカナ？？😘💗💫
楽しみだなぁ～♥😆👍🌸
![54380_main1](https://github.com/ououno/ichiyasaGitSample/assets/156639386/158f67c0-50d3-4329-9d36-b48305a87a10)

2024-01-16 05:32 UTC, sota777 requested changes

2024-01-16 05:32 UTC, sota777 commented on test.text
> +ゆでたまご
キン肉マンの作者か

2024-01-18 04:21 UTC, sota777 commented
たっくーん

2024-01-19 01:23 UTC, merged